default_install_hook_types: [commit-msg]
repos:
  - repo: local
    hooks:
      - id: conventional-commit-message
        name: conventional commit message
        entry: ./scripts/validate-commit-msg.sh
        language: system
        stages: [commit-msg]
